import { useState } from 'react';
import { useNavigate } from 'react-router';
import {
  AlertTriangle, Check, ChevronDown, Eye, EyeOff, FileText, KeyRound, LogOut, ShieldCheck,
} from 'lucide-react';
import { DarkHeader } from '../components/DarkHeader';
import { flushSave } from '../utils/db';
import { logout } from '../utils/authStorage';
import { getCurrentUser, isValidPin, updateUserPin, verifyUserPin } from '../utils/userStorage';
import { useAppEvents } from '../utils/useAppEvents';

type PolicyKey = 'privacy' | 'terms' | 'security';

const POLICIES: { key: PolicyKey; title: string; body: string[] }[] = [
  {
    key: 'privacy',
    title: 'Privacy policy',
    body: [
      'This prototype stores all of your data locally in your own browser, using SQLite compiled to WebAssembly with the database persisted in IndexedDB. Nothing is transmitted to a NETS server, and no analytics or tracking scripts are loaded.',
      'The data held includes your profile details, transactions, split bills, reminders, Hangout plans, reward redemptions and notification preferences. Clearing your browser storage, or using Clear All Data in Profile, deletes all of it permanently.',
      'A production release would store this data server-side under the Personal Data Protection Act, with a documented retention period and an export-and-delete request process.',
    ],
  },
  {
    key: 'terms',
    title: 'Terms of use',
    body: [
      'This application is a student prototype built for a NETS project presentation. It is not a licensed payment service, it holds no real money, and no transaction shown in it settles through a live payment network.',
      'Balances, XP, vouchers and merchant offers are simulated. Voucher codes generated by the Rewards store are not redeemable at any real merchant.',
      'Use of the prototype is limited to demonstration and evaluation. Do not enter real card numbers, bank details or any information you would not want stored unencrypted in your browser.',
    ],
  },
  {
    key: 'security',
    title: 'Security information',
    body: [
      'Sign-in uses a login ID and a 6-digit PIN. Repeated incorrect attempts temporarily lock the account, and PIN recovery verifies your registered mobile number before issuing a new PIN.',
      'Known limitation: because this prototype has no backend, PINs are stored unhashed in the local database and every browser holds its own isolated copy of the data. Recovery codes are shown on screen rather than delivered by SMS.',
      'A production deployment would require a secure backend with hashed credentials, server-side sessions, real one-time-password delivery, role-based authorisation for the management portal, and server-synchronised data across devices.',
    ],
  },
];

export function SecurityPrivacyPage() {
  const navigate = useNavigate();
  const [currentUser, setCurrentUser] = useState(getCurrentUser());
  const [currentPin, setCurrentPin] = useState('');
  const [newPin, setNewPin] = useState('');
  const [confirmPin, setConfirmPin] = useState('');
  const [showPins, setShowPins] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [openPolicy, setOpenPolicy] = useState<PolicyKey | null>(null);

  useAppEvents(['userSwitched'], () => setCurrentUser(getCurrentUser()));

  const digitsOnly = (value: string) => value.replace(/\D/g, '').slice(0, 6);
  const canSubmit = currentPin.length === 6 && isValidPin(newPin) && confirmPin.length === 6;

  const changePin = async () => {
    if (!canSubmit) return;
    if (!verifyUserPin(currentUser.id, currentPin)) {
      setStatus({ type: 'error', text: 'Your current PIN is incorrect.' });
      return;
    }
    if (newPin !== confirmPin) {
      setStatus({ type: 'error', text: 'The new PIN and confirmation do not match.' });
      return;
    }
    if (newPin === currentPin) {
      setStatus({ type: 'error', text: 'Choose a PIN different from your current one.' });
      return;
    }

    updateUserPin(currentUser.id, newPin);
    await flushSave();
    setCurrentPin('');
    setNewPin('');
    setConfirmPin('');
    setStatus({ type: 'success', text: 'Your PIN has been changed. Use it the next time you sign in.' });
  };

  const signOut = () => {
    logout();
    navigate('/login', { replace: true });
  };

  return (
    <div className="flex h-full flex-col bg-white">
      <DarkHeader title="Security & Privacy" onBack={() => navigate('/profile')} bottomGap="mb-5">
        <div className="flex items-center gap-3 rounded-2xl border border-white/20 bg-white/10 p-4 backdrop-blur-md">
          <div className="grid h-12 w-12 flex-shrink-0 place-items-center rounded-2xl bg-white/20">
            <ShieldCheck size={24} className="text-white" aria-hidden="true" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-black text-white">Signed in as {currentUser.name}</p>
            <p className="text-[11px] text-white/70">Login ID {currentUser.loginId ?? '—'}</p>
          </div>
        </div>
      </DarkHeader>

      <div className="flex-1 overflow-y-auto px-5 py-4 pb-8">
        <p className="sr-only" role="status" aria-live="polite">{status?.text ?? ''}</p>

        <section className="rounded-2xl border-2 border-border p-4">
          <div className="mb-3 flex items-center gap-2">
            <KeyRound size={17} className="text-primary" aria-hidden="true" />
            <h2 className="text-sm font-black text-foreground">Change your PIN</h2>
          </div>

          {status && (
            <div
              className={`mb-3 rounded-xl p-3 text-xs font-bold ${status.type === 'success' ? 'bg-success/10 text-success' : 'bg-destructive/10 text-destructive'}`}
            >
              <span className="flex items-start gap-1.5">
                {status.type === 'success'
                  ? <Check size={14} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
                  : <AlertTriangle size={14} className="mt-0.5 flex-shrink-0" aria-hidden="true" />}
                {status.text}
              </span>
            </div>
          )}

          <div className="space-y-3">
            <div>
              <label htmlFor="current-pin" className="mb-1 block text-xs font-black">Current PIN</label>
              <input
                id="current-pin"
                type={showPins ? 'text' : 'password'}
                inputMode="numeric"
                autoComplete="current-password"
                value={currentPin}
                onChange={event => setCurrentPin(digitsOnly(event.target.value))}
                className="w-full rounded-xl border-2 border-border px-4 py-3 font-mono text-sm tracking-[0.3em] outline-none focus:border-primary"
              />
            </div>
            <div>
              <label htmlFor="new-pin" className="mb-1 block text-xs font-black">New 6-digit PIN</label>
              <input
                id="new-pin"
                type={showPins ? 'text' : 'password'}
                inputMode="numeric"
                autoComplete="new-password"
                value={newPin}
                onChange={event => setNewPin(digitsOnly(event.target.value))}
                className="w-full rounded-xl border-2 border-border px-4 py-3 font-mono text-sm tracking-[0.3em] outline-none focus:border-primary"
              />
            </div>
            <div>
              <label htmlFor="confirm-pin" className="mb-1 block text-xs font-black">Confirm new PIN</label>
              <input
                id="confirm-pin"
                type={showPins ? 'text' : 'password'}
                inputMode="numeric"
                autoComplete="new-password"
                value={confirmPin}
                onChange={event => setConfirmPin(digitsOnly(event.target.value))}
                className="w-full rounded-xl border-2 border-border px-4 py-3 font-mono text-sm tracking-[0.3em] outline-none focus:border-primary"
              />
            </div>
          </div>

          <button
            onClick={() => setShowPins(current => !current)}
            className="mt-2 flex min-h-11 items-center gap-1.5 text-xs font-bold text-muted-foreground"
          >
            {showPins
              ? <><EyeOff size={13} aria-hidden="true" /> Hide PINs</>
              : <><Eye size={13} aria-hidden="true" /> Show PINs</>}
          </button>

          <button
            onClick={changePin}
            disabled={!canSubmit}
            className="mt-2 w-full rounded-2xl bg-primary py-3.5 text-sm font-black text-white disabled:opacity-40"
          >
            Update PIN
          </button>

          <button
            onClick={() => navigate('/recover-pin')}
            className="mt-2 min-h-11 w-full text-xs font-bold text-primary"
          >
            Forgot your current PIN? Recover it instead
          </button>
        </section>

        <section className="mt-4">
          <h2 className="mb-2 text-xs font-black uppercase tracking-wider text-muted-foreground">
            Policies &amp; disclosures
          </h2>
          <div className="space-y-2">
            {POLICIES.map(policy => {
              const open = openPolicy === policy.key;
              return (
                <div key={policy.key} className="overflow-hidden rounded-2xl border-2 border-border">
                  <button
                    onClick={() => setOpenPolicy(open ? null : policy.key)}
                    aria-expanded={open}
                    className="flex min-h-11 w-full items-center gap-3 p-4 text-left"
                  >
                    <FileText size={17} className="flex-shrink-0 text-primary" aria-hidden="true" />
                    <span className="flex-1 text-sm font-black text-foreground">{policy.title}</span>
                    <ChevronDown
                      size={16}
                      className={`flex-shrink-0 text-muted-foreground transition-transform ${open ? 'rotate-180' : ''}`}
                      aria-hidden="true"
                    />
                  </button>
                  {open && (
                    <div className="space-y-2 border-t border-border px-4 py-3">
                      {policy.body.map((paragraph, index) => (
                        <p key={index} className="text-[11px] leading-relaxed text-muted-foreground">
                          {paragraph}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        <button
          onClick={signOut}
          className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-border py-3.5 text-sm font-black text-foreground"
        >
          <LogOut size={16} aria-hidden="true" /> Sign out of this device
        </button>
      </div>
    </div>
  );
}
