import { defineConfig } from 'vite'
import path from 'path'
import fs from 'fs'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'


function figmaAssetResolver() {
  return {
    name: 'figma-asset-resolver',
    resolveId(id: string) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        return path.resolve(__dirname, 'src/assets', filename)
      }
    },
  }
}

// ── Dev-only: mirror the LIVE browser database to files in /database ──────────
// The app runs SQLite in the browser (sql.js + IndexedDB), so it can't write to
// disk by itself. During `npm run dev`, the app POSTs a snapshot to /__db/save
// after every change and this middleware writes it out. Nothing is hard-coded:
// whatever the app actually contains (after any add / edit / delete) is what
// lands in these files:
//   database/nets.sqlite        - the real SQLite file (open in DB Browser / VS)
//   database/snapshot.md        - every table as a readable grid
//   database/tables/<name>.csv  - one CSV per table
// This plugin does nothing in a production build.

type SnapshotTable = { name: string; columns: string[]; rows: (string | number | null)[][] }

function cell(value: string | number | null): string {
  return value === null || value === undefined ? '' : String(value)
}

function renderMarkdown(tables: SnapshotTable[]): string {
  const lines: string[] = [
    '# NETS database snapshot',
    '',
    `_Auto-generated by \`npm run dev\` — last updated ${new Date().toISOString()}._`,
    '',
    'This mirrors the live app database. Use the app (add / edit / delete) and it',
    'rewrites itself. No rows here are hard-coded.',
    '',
  ]
  for (const table of tables) {
    lines.push(`## ${table.name}  (${table.rows.length} rows)`, '')
    if (table.columns.length === 0) { lines.push('_(no columns)_', ''); continue }
    lines.push(`| ${table.columns.join(' | ')} |`)
    lines.push(`| ${table.columns.map(() => '---').join(' | ')} |`)
    for (const row of table.rows) {
      lines.push(`| ${row.map(v => cell(v).replace(/\|/g, '\\|').replace(/\n/g, ' ')).join(' | ')} |`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

function renderCsv(table: SnapshotTable): string {
  const esc = (v: string | number | null): string => {
    const t = cell(v)
    return /[",\n]/.test(t) ? `"${t.replace(/"/g, '""')}"` : t
  }
  return [table.columns.map(esc).join(','), ...table.rows.map(r => r.map(esc).join(','))].join('\n')
}

function databaseFileWriter() {
  return {
    name: 'database-file-writer',
    configureServer(server: any) {
      server.middlewares.use('/__db/save', (req: any, res: any) => {
        if (req.method !== 'POST') { res.statusCode = 405; res.end('Method Not Allowed'); return }
        let body = ''
        req.on('data', (chunk: any) => { body += chunk })
        req.on('end', () => {
          try {
            const { sqlite, snapshot } = JSON.parse(body) as { sqlite?: string; snapshot: SnapshotTable[] }
            const dir = path.resolve(__dirname, 'database')
            const tablesDir = path.resolve(dir, 'tables')
            fs.mkdirSync(tablesDir, { recursive: true })

            if (sqlite) fs.writeFileSync(path.resolve(dir, 'nets.sqlite'), Buffer.from(sqlite, 'base64'))
            fs.writeFileSync(path.resolve(dir, 'snapshot.md'), renderMarkdown(snapshot))

            for (const file of fs.readdirSync(tablesDir)) {
              if (file.endsWith('.csv')) fs.unlinkSync(path.resolve(tablesDir, file))
            }
            for (const table of snapshot) {
              fs.writeFileSync(path.resolve(tablesDir, `${table.name}.csv`), renderCsv(table))
            }
            res.statusCode = 200; res.end('ok')
          } catch (err) {
            res.statusCode = 500; res.end(String(err))
          }
        })
      })
    },
  }
}

export default defineConfig({
  // Pin the dev server to a fixed port. The app stores its database in the
  // browser's IndexedDB, which is scoped to the exact origin (host + port). If
  // the port changed between runs, the browser would treat it as a different
  // site and the saved data would appear to reset. strictPort keeps the URL
  // stable so data persists across `npm run dev` restarts, refreshes, and
  // browser closes.
  server: {
    port: 5173,
    strictPort: true,
  },
  plugins: [
    figmaAssetResolver(),
    databaseFileWriter(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
